-- AlterTable
ALTER TABLE "Todo" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "createdAt" SET DATA TYPE TEXT,
ALTER COLUMN "dueDate" SET DATA TYPE TEXT,
ALTER COLUMN "completedAt" SET DATA TYPE TEXT;
